package UI.AdminRole;

/**
 *
 * @author sid
 */
public class EnterpriseAdminWorkArea extends javax.swing.JPanel {

  /**
   * Creates new form EnterpriseAdminWorkArea
   */
  public EnterpriseAdminWorkArea() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel1 = new javax.swing.JLabel();
    userJButton = new javax.swing.JButton();
    manageEmployeeJButton = new javax.swing.JButton();
    manageOrganizationJButton = new javax.swing.JButton();
    enterpriseLabel = new javax.swing.JLabel();
    btnRequestFunds = new javax.swing.JButton();
    btnRequestOrder = new javax.swing.JButton();

    setBackground(new java.awt.Color(190, 194, 224));

    jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
    jLabel1.setForeground(new java.awt.Color(255, 255, 255));
    jLabel1.setText("My Work Area -Adminstrative Role");

    userJButton.setBackground(new java.awt.Color(250, 218, 209));
    userJButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
    userJButton.setText("Manage User");
    userJButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        userJButtonActionPerformed(evt);
      }
    });

    manageEmployeeJButton.setBackground(new java.awt.Color(250, 218, 209));
    manageEmployeeJButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
    manageEmployeeJButton.setText("Manage Employee");
    manageEmployeeJButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        manageEmployeeJButtonActionPerformed(evt);
      }
    });

    manageOrganizationJButton.setBackground(new java.awt.Color(250, 218, 209));
    manageOrganizationJButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
    manageOrganizationJButton.setText("Manage Organization");
    manageOrganizationJButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        manageOrganizationJButtonActionPerformed(evt);
      }
    });

    enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
    enterpriseLabel.setForeground(new java.awt.Color(255, 255, 255));
    enterpriseLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    enterpriseLabel.setText("Enterprise ");

    btnRequestFunds.setBackground(new java.awt.Color(250, 218, 209));
    btnRequestFunds.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
    btnRequestFunds.setText("Request Funds from Government");
    btnRequestFunds.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnRequestFundsActionPerformed(evt);
      }
    });

    btnRequestOrder.setBackground(new java.awt.Color(250, 218, 209));
    btnRequestOrder.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
    btnRequestOrder.setText("Order Medicine and Equipment");
    btnRequestOrder.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnRequestOrderActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(enterpriseLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 582, Short.MAX_VALUE)
      .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
          .addGap(0, 0, Short.MAX_VALUE)
          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
            .addGroup(layout.createSequentialGroup()
              .addGap(70, 70, 70)
              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(manageOrganizationJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(manageEmployeeJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(userJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnRequestOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnRequestFunds, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))))
          .addGap(0, 0, Short.MAX_VALUE)))
    );

    layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnRequestFunds, btnRequestOrder, manageEmployeeJButton, manageOrganizationJButton, userJButton});

    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(127, 127, 127)
        .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(450, Short.MAX_VALUE))
      .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
          .addGap(0, 0, Short.MAX_VALUE)
          .addComponent(jLabel1)
          .addGap(91, 91, 91)
          .addComponent(manageOrganizationJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGap(20, 20, 20)
          .addComponent(manageEmployeeJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGap(20, 20, 20)
          .addComponent(userJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGap(20, 20, 20)
          .addComponent(btnRequestOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGap(30, 30, 30)
          .addComponent(btnRequestFunds, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGap(0, 0, Short.MAX_VALUE)))
    );

    layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnRequestFunds, btnRequestOrder, manageEmployeeJButton, manageOrganizationJButton, userJButton});

  }// </editor-fold>//GEN-END:initComponents

    private void userJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userJButtonActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_userJButtonActionPerformed

    private void manageEmployeeJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageEmployeeJButtonActionPerformed

        
    }//GEN-LAST:event_manageEmployeeJButtonActionPerformed

    private void manageOrganizationJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageOrganizationJButtonActionPerformed

        
    }//GEN-LAST:event_manageOrganizationJButtonActionPerformed

    private void btnRequestFundsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestFundsActionPerformed

        
    }//GEN-LAST:event_btnRequestFundsActionPerformed

    private void btnRequestOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestOrderActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnRequestOrderActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnRequestFunds;
  private javax.swing.JButton btnRequestOrder;
  private javax.swing.JLabel enterpriseLabel;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JButton manageEmployeeJButton;
  private javax.swing.JButton manageOrganizationJButton;
  private javax.swing.JButton userJButton;
  // End of variables declaration//GEN-END:variables
}
