/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.AdminRole;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

import ChemoCare.Employee.Employee;
import ChemoCare.Org.Org;
import ChemoCare.Org.OrgDirectory;
import ChemoCare.Org.PatientOrg;

/**
 *
 * @author harshita
 */
public class ManageEmployeesJPanel extends javax.swing.JPanel {

    private OrgDirectory organizationDir;
    private JPanel userProcessContainer;
    /**
     * Creates new form ManageEmployeesJPanel
     */
     public ManageEmployeesJPanel(JPanel userProcessContainer,OrgDirectory organizationDir) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organizationDir = organizationDir;
        
        populateOrganizationComboBox();
        populateOrganizationEmpComboBox();
    }

      public void populateOrganizationComboBox(){
        cmbOrganization.removeAllItems();
        
        for (Org organization : organizationDir.getOrganizations()){
            
            if(!(organization instanceof PatientOrg))
            cmbOrganizationEmployee.addItem(organization);
        }
    }
      
        public void populateOrganizationEmpComboBox(){
        cmbOrganizationEmployee.removeAllItems();
        
        for (Org organization : organizationDir.getOrganizations()){
            
             if(!(organization instanceof PatientOrg))
            cmbOrganizationEmployee.addItem(organization);
        }
    }
        
      
    private void populateTable(Org organization){
        DefaultTableModel model = (DefaultTableModel) tblOrganization.getModel();
        
        model.setRowCount(0);
        
        for (Employee employee : organization.getEmployeeDirectory().getEmpList()){
            Object[] row = new Object[2];
            row[0] = employee.getEmpID();
            row[1] = employee.getEmpName();
            model.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jScrollPane1 = new javax.swing.JScrollPane();
    tblOrganization = new javax.swing.JTable();
    btnAddEmployee = new javax.swing.JButton();
    cmbOrganization = new javax.swing.JComboBox();
    jLabel1 = new javax.swing.JLabel();
    btnBack = new javax.swing.JButton();
    jLabel2 = new javax.swing.JLabel();
    txtName = new javax.swing.JTextField();
    cmbOrganizationEmployee = new javax.swing.JComboBox();
    jLabel3 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    jLabel6 = new javax.swing.JLabel();

    setBackground(new java.awt.Color(255, 255, 255));

    tblOrganization.setBackground(new java.awt.Color(209, 223, 241));
    tblOrganization.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {
        {null, null},
        {null, null},
        {null, null},
        {null, null}
      },
      new String [] {
        "ID", "Name"
      }
    ) {
      Class[] types = new Class [] {
        java.lang.String.class, java.lang.String.class
      };
      boolean[] canEdit = new boolean [] {
        false, false
      };

      public Class getColumnClass(int columnIndex) {
        return types [columnIndex];
      }

      public boolean isCellEditable(int rowIndex, int columnIndex) {
        return canEdit [columnIndex];
      }
    });
    jScrollPane1.setViewportView(tblOrganization);
    if (tblOrganization.getColumnModel().getColumnCount() > 0) {
      tblOrganization.getColumnModel().getColumn(0).setPreferredWidth(15);
    }

    btnAddEmployee.setBackground(new java.awt.Color(64, 123, 255));
    btnAddEmployee.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
    btnAddEmployee.setForeground(new java.awt.Color(255, 255, 255));
    btnAddEmployee.setText("Create Employee");
    btnAddEmployee.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnAddEmployeeActionPerformed(evt);
      }
    });

    cmbOrganization.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        cmbOrganizationActionPerformed(evt);
      }
    });

    jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    jLabel1.setForeground(new java.awt.Color(64, 123, 255));
    jLabel1.setText("Check For");

    btnBack.setBackground(new java.awt.Color(64, 123, 255));
    btnBack.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
    btnBack.setForeground(new java.awt.Color(255, 255, 255));
    btnBack.setText("<< Back");
    btnBack.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnBackActionPerformed(evt);
      }
    });

    jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    jLabel2.setForeground(new java.awt.Color(64, 123, 255));
    jLabel2.setText("Name");

    jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    jLabel3.setForeground(new java.awt.Color(64, 123, 255));
    jLabel3.setText("Organization");

    jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
    jLabel4.setForeground(new java.awt.Color(64, 123, 255));
    jLabel4.setText("Manage Employee");

    jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Assets/image 30.png"))); // NOI18N

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap(163, Short.MAX_VALUE)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel4))
              .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                  .addGroup(layout.createSequentialGroup()
                    .addComponent(jLabel2)
                    .addGap(44, 44, 44)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addGroup(layout.createSequentialGroup()
                    .addComponent(jLabel3)
                    .addGap(44, 44, 44)
                    .addComponent(cmbOrganizationEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))))
              .addGroup(layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(btnAddEmployee))
              .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(65, 65, 65)
                .addComponent(cmbOrganization, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 674, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addComponent(btnBack, javax.swing.GroupLayout.Alignment.TRAILING))
        .addGap(19, 19, 19))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addGap(14, 14, 14)
            .addComponent(btnBack)
            .addGap(108, 108, 108)
            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(layout.createSequentialGroup()
            .addGap(137, 137, 137)
            .addComponent(jLabel4)
            .addGap(53, 53, 53)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel1))
              .addComponent(cmbOrganization, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(29, 29, 29)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(31, 31, 31)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel3))
              .addComponent(cmbOrganizationEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel2))
              .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(27, 27, 27)
            .addComponent(btnAddEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap(102, Short.MAX_VALUE))
    );
  }// </editor-fold>//GEN-END:initComponents

    private void btnAddEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddEmployeeActionPerformed
            
                Org organization = (Org) cmbOrganizationEmployee.getSelectedItem();
        String name = txtName.getText();
        if(name == null || name.equals("")){
            JOptionPane.showMessageDialog(null, "Name Cannot be empty!");
            return;
        }    
        organization.getEmployeeDirectory().createEmployee(name);
        populateTable(organization);
        txtName.setText("");
        JOptionPane.showMessageDialog(null, "Employee created!");
        
    }//GEN-LAST:event_btnAddEmployeeActionPerformed

    private void cmbOrganizationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbOrganizationActionPerformed
  Org organization = (Org) cmbOrganization.getSelectedItem();
        if (organization != null){
            populateTable(organization);
        }        
    }//GEN-LAST:event_cmbOrganizationActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnAddEmployee;
  private javax.swing.JButton btnBack;
  private javax.swing.JComboBox cmbOrganization;
  private javax.swing.JComboBox cmbOrganizationEmployee;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTable tblOrganization;
  private javax.swing.JTextField txtName;
  // End of variables declaration//GEN-END:variables
}
