/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.HealthcareAccountant;

import ChemoCare.Ecosystem;
import ChemoCare.Enterprise.Enterprise;
import ChemoCare.Enterprise.InsuranceCompanyEnterprise;
import ChemoCare.Insurance.Insurance;
import ChemoCare.InsuranceCustomer.InsuranceCustomer;
import ChemoCare.Map.SMS;
import ChemoCare.Map.SendEmail;
import ChemoCare.NetworkSystem.NetworkSystem;
import ChemoCare.Org.AccountantOrg;
import ChemoCare.Org.InsuranceAgentOrg;
import ChemoCare.Org.Org;
import ChemoCare.Account.Account;
import ChemoCare.JobQueue.AccountsBillingJob;
import ChemoCare.JobQueue.InsuranceJob;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author harshita
 */
public class AccountantProcessRequestJPanel extends javax.swing.JPanel {
   private JPanel userProcessContainer;
    private Account account;
    private Enterprise enterprise;
    private AccountantOrg accountantOrg;
    private AccountsBillingJob accountBillingJob;
    private Ecosystem ecosystem;
    private double payableAmount;
    /**
     * Creates new form AccountantJPanel
     */
    public AccountantProcessRequestJPanel(JPanel userProcessContainer, Account account, AccountsBillingJob request, Enterprise enterprise, Ecosystem ecosystem) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.enterprise = enterprise;
        this.accountantOrg = accountantOrg;
        this.accountBillingJob = request;
        this.ecosystem = ecosystem;
        populate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnSendRequestForInsurance = new javax.swing.JButton();
        txtSSN = new javax.swing.JTextField();
        txtInsurancePolicyName = new javax.swing.JTextField();
        txtPayableAmount = new javax.swing.JTextField();
        txtFirstName = new javax.swing.JTextField();
        txtBillAmount = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        txtPolicyNumber = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtInsuranceClaimAmount = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        btnCollectCash = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Process Billing Request Area");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("SSN");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("FirstName");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("LastName");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Bill Amount");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Insurance Policy Name");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Payable Amount");

        btnSendRequestForInsurance.setBackground(new java.awt.Color(250, 218, 209));
        btnSendRequestForInsurance.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSendRequestForInsurance.setText("Receive Amount / Send request for Insurance Claim");
        btnSendRequestForInsurance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendRequestForInsuranceActionPerformed(evt);
            }
        });

        txtSSN.setEditable(false);

        txtInsurancePolicyName.setEditable(false);

        txtPayableAmount.setEditable(false);

        txtFirstName.setEditable(false);

        txtBillAmount.setEditable(false);

        txtLastName.setEditable(false);

        txtPolicyNumber.setEditable(false);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Policy Number");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Insurance Claim Amount");

        txtInsuranceClaimAmount.setEditable(false);

        btnBack.setBackground(new java.awt.Color(250, 218, 209));
        btnBack.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnCollectCash.setBackground(new java.awt.Color(250, 218, 209));
        btnCollectCash.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCollectCash.setText("Receive complete amount from patient");
        btnCollectCash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCollectCashActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addComponent(jLabel8)
                        .addGap(52, 52, 52)
                        .addComponent(txtPolicyNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jLabel6)
                        .addGap(52, 52, 52)
                        .addComponent(txtInsurancePolicyName, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(261, 261, 261)
                        .addComponent(jLabel2)
                        .addGap(52, 52, 52)
                        .addComponent(txtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(jLabel3)
                        .addGap(52, 52, 52)
                        .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(227, 227, 227)
                        .addComponent(jLabel4)
                        .addGap(52, 52, 52)
                        .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addComponent(jLabel5)
                        .addGap(52, 52, 52)
                        .addComponent(txtBillAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(jLabel9)
                        .addGap(52, 52, 52)
                        .addComponent(txtInsuranceClaimAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(jLabel7)
                        .addGap(52, 52, 52)
                        .addComponent(txtPayableAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(btnSendRequestForInsurance)
                        .addGap(32, 32, 32)
                        .addComponent(btnCollectCash)))
                .addGap(46, 46, 46))
            .addComponent(btnBack, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel8))
                    .addComponent(txtPolicyNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel6))
                    .addComponent(txtInsurancePolicyName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel2))
                    .addComponent(txtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel3))
                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel4))
                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel5))
                    .addComponent(txtBillAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel9))
                    .addComponent(txtInsuranceClaimAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel7))
                    .addComponent(txtPayableAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSendRequestForInsurance, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCollectCash, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSendRequestForInsuranceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendRequestForInsuranceActionPerformed
    String policyNumber = accountBillingJob.getPatient().getInsuranceCustomer().getInsurancePlanNumber();
        String ssn = accountBillingJob.getPatient().getSSN();
        String policyName = accountBillingJob.getPatient().getInsuranceCustomer().getInsurance().getPlanName();
        String insuranceCompany = accountBillingJob.getPatient().getInsuranceCustomer().getInsurance().getInsuranceCompany();
        String email = accountBillingJob.getPatient().getPatientEmail();
        String phone = accountBillingJob.getPatient().getPhoneNumber();
        double claimAmount = Double.parseDouble(txtInsuranceClaimAmount.getText());
        double billAmount = accountBillingJob.getBillingAmt();
        String sub="Your Medical Bill is Processed";


       
            Insurance insurance = new Insurance(policyName, insuranceCompany, claimAmount);
            insurance.setReimbursement(accountBillingJob.getPatient().getInsuranceCustomer().getInsurance().getReimbursement());

            InsuranceCustomer insuranceCustomer = new InsuranceCustomer(insurance, policyNumber);
            insuranceCustomer.setCustomerFName(txtFirstName.getText().trim());
            insuranceCustomer.setCustomerLName((txtLastName.getText().trim()));

            InsuranceJob insuranceWorkRequest = new InsuranceJob();
            insuranceWorkRequest.setInsuranceCompany(insuranceCompany);
            insuranceWorkRequest.setPolicyNumber(policyNumber);
            insuranceWorkRequest.setPolicyName(policyName);
            insuranceWorkRequest.setSsn(ssn);
            insuranceWorkRequest.setClaimAmount(claimAmount);
            insuranceWorkRequest.setBillAmount(billAmount);
            insuranceWorkRequest.setHealthCenter(enterprise.getOrgName());

            insuranceWorkRequest.setSender(account);
            insuranceWorkRequest.setStatus("Sent");
            insuranceWorkRequest.setInsuranceCustomer(insuranceCustomer);
            insuranceWorkRequest.setCustomerEmail(email);
            insuranceWorkRequest.setCustomerPhone(phone);
            
            Org org = null;
            InsuranceCompanyEnterprise matchedInsuranceCompany = null;

            List<NetworkSystem> networks = ecosystem.getNetworkSystems();
            for (NetworkSystem network : networks) {
                List<Enterprise> enterprises = network.getEnterpriseDirectory().getEnterpriseList();
                for (Enterprise enterprise : enterprises) {
                    if (enterprise.getOrgName().equalsIgnoreCase(accountBillingJob.getPatient().getInsuranceCustomer().getInsurance().getInsuranceCompany())) {
                        matchedInsuranceCompany = (InsuranceCompanyEnterprise) enterprise;
                    }
                }
            }

            for (Org organization : matchedInsuranceCompany.getOrgDirectory().getOrganizations()) {
                if (organization instanceof InsuranceAgentOrg) {
                    org = organization;
                    break;
                }
            }
            if (org != null) {
                org.getJobQueue().getJobRequestList().add(insuranceWorkRequest);
                account.getJobQueue().getJobRequestList().add(insuranceWorkRequest);
                accountBillingJob.setStatus("Patient Transaction Completed");
                accountBillingJob.getPatient().setIsTreatmentDone(true);
                accountBillingJob.getVisitRequest().setIsComplete(true);
                try{
                SendEmail.send(accountBillingJob.getPatient().getPatientEmail(),"\nHi "+accountBillingJob.getPatient().getPatientFName()+","+"\n\nYour Medical bill of amount: "+ accountBillingJob.getBillingAmt()+
                        " is processed"+"\n\n\nThanks\n"+enterprise.getOrgName(),sub);
            }catch(Exception ex){
                    JOptionPane.showMessageDialog(null, "Email Could not be sent due to technical issues");
                    System.out.println(ex.getMessage());
                }
        //Send SMS
                try{
                    SMS.SendSMS("+16176524988","Hi "+accountBillingJob.getPatient().getPatientFName()+","+"\nYour Medical Bill of amount: "+ accountBillingJob.getBillingAmt()+
                        " is processed"+"\n\nThanks,\n"+enterprise.getOrgName());
                }catch (Exception e){
                     System.out.println(e.getMessage());
                }
         //Send SMS end
         JOptionPane.showMessageDialog(null, "Money received from patient: " + payableAmount+". Insurance Claim Request Raised Successfully for amount:" + claimAmount);
                
           btnSendRequestForInsurance.setEnabled(false);
            }
    }//GEN-LAST:event_btnSendRequestForInsuranceActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed

    }//GEN-LAST:event_btnBackActionPerformed

    private void btnCollectCashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCollectCashActionPerformed
String sub="Your Medical Bill is Processed";
        accountBillingJob.setStatus("Patient Transaction Completed");
        accountBillingJob.getPatient().setIsTreatmentDone(true);
        accountBillingJob.getVisitRequest().setIsComplete(true);
        try{
                SendEmail.send(accountBillingJob.getPatient().getPatientEmail(),"\nHi "+accountBillingJob.getPatient().getPatientFName()+","+"\n\nYour Medical bill of amount: "+ accountBillingJob.getBillingAmt()+
                        " is processed"+"\n\n\nThanks\n"+enterprise.getOrgName(),sub);
            }catch(Exception ex){
                    JOptionPane.showMessageDialog(null, "Email Could not be sent due to technical issues");
                    System.out.println(ex.getMessage());
                }
        //Send SMS
                try{
                    SMS.SendSMS("+14793190560","Hi "+accountBillingJob.getPatient().getPatientFName()+","+"\nYour Medical Bill of amount: "+ accountBillingJob.getBillingAmt()+
                        " is processed"+"\n\nThanks,\n"+enterprise.getOrgName());
                }catch (Exception e){
                     System.out.println(e.getMessage());
                }
         //Send SMS end
        JOptionPane.showMessageDialog(null, "Amount received from Patient");
        btnCollectCash.setEnabled(false);        
    }//GEN-LAST:event_btnCollectCashActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCollectCash;
    private javax.swing.JButton btnSendRequestForInsurance;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtBillAmount;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtInsuranceClaimAmount;
    private javax.swing.JTextField txtInsurancePolicyName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtPayableAmount;
    private javax.swing.JTextField txtPolicyNumber;
    private javax.swing.JTextField txtSSN;
    // End of variables declaration//GEN-END:variables
 private void populate() {
        String policyNumber = accountBillingJob.getPatient().getInsuranceCustomer().getInsurancePlanNumber();
        double coverage = accountBillingJob.getPatient().getInsuranceCustomer().getInsurance().getReimbursement();
        double billAmount = accountBillingJob.getBillingAmt();
        String ssn = accountBillingJob.getPatient().getSSN();
        String policyName = accountBillingJob.getPatient().getInsuranceCustomer().getInsurance().getPlanName();
        String insuranceCompany = accountBillingJob.getPatient().getInsuranceCustomer().getInsurance().getInsuranceCompany();
        double claimAmount = (coverage * billAmount) / 100;
        payableAmount = billAmount - claimAmount;

        txtPolicyNumber.setText(policyNumber);
        txtSSN.setText(ssn);
        txtFirstName.setText(accountBillingJob.getPatient().getPatientFName());
        txtLastName.setText(accountBillingJob.getPatient().getPatientLName());
        txtBillAmount.setText(String.valueOf(billAmount));
        txtInsurancePolicyName.setText(policyName);
        txtInsuranceClaimAmount.setText(String.valueOf(claimAmount));
        txtPayableAmount.setText(String.valueOf(payableAmount));
        
        if(claimAmount>0)
        {
            btnSendRequestForInsurance.setEnabled(true);
            btnCollectCash.setEnabled(false);
        }
        else
        {
            btnCollectCash.setEnabled(true);
            btnSendRequestForInsurance.setEnabled(false);
        }

    }


}
