/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.DoctorRole;

/**
 *
 * @author harshita
 */
public class RequestBillingsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form RequestBillingsJPanel
     */
    public RequestBillingsJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtPatientId = new javax.swing.JTextField();
        backBtn = new javax.swing.JButton();
        lblBillintInformationTitle = new javax.swing.JLabel();
        lblConsulationCharges = new javax.swing.JLabel();
        txtConsultationCharges = new javax.swing.JTextField();
        lblMedicationCharges = new javax.swing.JLabel();
        txtMedicationCharges = new javax.swing.JTextField();
        lblLabTest = new javax.swing.JLabel();
        lblBillingRequest = new javax.swing.JLabel();
        txtLabCharges = new javax.swing.JTextField();
        lblSubTitle = new javax.swing.JLabel();
        lblMiscellaneousCharges = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        txtMiscellaneousCharges = new javax.swing.JTextField();
        lblFirstName = new javax.swing.JLabel();
        btnSendBillingRequest = new javax.swing.JButton();
        lblLastName = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();
        lblAssignedDoctor = new javax.swing.JLabel();
        txtAssignedDoctor = new javax.swing.JTextField();
        lblPatientId = new javax.swing.JLabel();

        txtPatientId.setEditable(false);

        backBtn.setBackground(new java.awt.Color(250, 218, 209));
        backBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        backBtn.setText("<<Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        lblBillintInformationTitle.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblBillintInformationTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblBillintInformationTitle.setText("BILLING INFORMATION");

        lblConsulationCharges.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblConsulationCharges.setForeground(new java.awt.Color(255, 255, 255));
        lblConsulationCharges.setText("Consultaion Charges (USD) :");

        txtConsultationCharges.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConsultationChargesActionPerformed(evt);
            }
        });

        lblMedicationCharges.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblMedicationCharges.setForeground(new java.awt.Color(255, 255, 255));
        lblMedicationCharges.setText("Medication Charges (USD):");

        lblLabTest.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblLabTest.setForeground(new java.awt.Color(255, 255, 255));
        lblLabTest.setText("Lab Test Charges (USD) :");

        lblBillingRequest.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblBillingRequest.setForeground(new java.awt.Color(255, 255, 255));
        lblBillingRequest.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBillingRequest.setText("Billing Request");

        txtLabCharges.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLabChargesActionPerformed(evt);
            }
        });

        lblSubTitle.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblSubTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblSubTitle.setText("PATIENT INFORMATION");

        lblMiscellaneousCharges.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblMiscellaneousCharges.setForeground(new java.awt.Color(255, 255, 255));
        lblMiscellaneousCharges.setText("Miscellaneous Charges (USD):");

        txtFirstName.setEditable(false);

        lblFirstName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblFirstName.setForeground(new java.awt.Color(255, 255, 255));
        lblFirstName.setText("First Name :");

        btnSendBillingRequest.setBackground(new java.awt.Color(250, 218, 209));
        btnSendBillingRequest.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSendBillingRequest.setText("Send Billing Request");
        btnSendBillingRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendBillingRequestActionPerformed(evt);
            }
        });

        lblLastName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblLastName.setForeground(new java.awt.Color(255, 255, 255));
        lblLastName.setText("Last Name :");

        txtLastName.setEditable(false);

        lblAssignedDoctor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblAssignedDoctor.setForeground(new java.awt.Color(255, 255, 255));
        lblAssignedDoctor.setText("Assigned Doctor :");

        txtAssignedDoctor.setEditable(false);

        lblPatientId.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblPatientId.setForeground(new java.awt.Color(255, 255, 255));
        lblPatientId.setText("Patient Id:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(488, 488, 488)
                .addComponent(backBtn))
            .addComponent(lblBillingRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(269, 269, 269)
                .addComponent(lblSubTitle))
            .addGroup(layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(lblFirstName)
                .addGap(6, 6, 6)
                .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(lblLastName)
                .addGap(6, 6, 6)
                .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(lblAssignedDoctor)
                .addGap(6, 6, 6)
                .addComponent(txtAssignedDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(lblPatientId)
                .addGap(6, 6, 6)
                .addComponent(txtPatientId, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(273, 273, 273)
                .addComponent(lblBillintInformationTitle))
            .addGroup(layout.createSequentialGroup()
                .addGap(208, 208, 208)
                .addComponent(lblConsulationCharges)
                .addGap(10, 10, 10)
                .addComponent(txtConsultationCharges, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(229, 229, 229)
                .addComponent(lblLabTest)
                .addGap(10, 10, 10)
                .addComponent(txtLabCharges, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(217, 217, 217)
                .addComponent(lblMedicationCharges)
                .addGap(10, 10, 10)
                .addComponent(txtMedicationCharges, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(199, 199, 199)
                .addComponent(lblMiscellaneousCharges)
                .addGap(10, 10, 10)
                .addComponent(txtMiscellaneousCharges, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(277, 277, 277)
                .addComponent(btnSendBillingRequest))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(backBtn)
                .addGap(26, 26, 26)
                .addComponent(lblBillingRequest)
                .addGap(30, 30, 30)
                .addComponent(lblSubTitle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFirstName)
                            .addComponent(lblLastName))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAssignedDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPatientId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAssignedDoctor)
                            .addComponent(lblPatientId))))
                .addGap(18, 18, 18)
                .addComponent(lblBillintInformationTitle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblConsulationCharges)
                    .addComponent(txtConsultationCharges, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblLabTest))
                    .addComponent(txtLabCharges, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblMedicationCharges))
                    .addComponent(txtMedicationCharges, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblMiscellaneousCharges))
                    .addComponent(txtMiscellaneousCharges, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(btnSendBillingRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed

    }//GEN-LAST:event_backBtnActionPerformed

    private void txtConsultationChargesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConsultationChargesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConsultationChargesActionPerformed

    private void txtLabChargesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLabChargesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLabChargesActionPerformed

    private void btnSendBillingRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendBillingRequestActionPerformed

    }//GEN-LAST:event_btnSendBillingRequestActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton btnSendBillingRequest;
    private javax.swing.JLabel lblAssignedDoctor;
    private javax.swing.JLabel lblBillingRequest;
    private javax.swing.JLabel lblBillintInformationTitle;
    private javax.swing.JLabel lblConsulationCharges;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblLabTest;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblMedicationCharges;
    private javax.swing.JLabel lblMiscellaneousCharges;
    private javax.swing.JLabel lblPatientId;
    private javax.swing.JLabel lblSubTitle;
    private javax.swing.JTextField txtAssignedDoctor;
    private javax.swing.JTextField txtConsultationCharges;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLabCharges;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtMedicationCharges;
    private javax.swing.JTextField txtMiscellaneousCharges;
    private javax.swing.JTextField txtPatientId;
    // End of variables declaration//GEN-END:variables
}
